const CATEGORIES=['言语理解','图表分析','图形推理','综合真题','情景判断','性格测试'];
const DESCRIPTIONS=['段落理解 · 逻辑填空','数据比较 · 增长计算','规律识别 · 空间思维','按原卷顺序练习','职场场景 · 决策练习','了解自己的行为偏好'];
const ICONS=['文','表','图','卷','景','心'];
const STORE='ten-question-practice-v1';
const root=document.querySelector('#app'),dialog=document.querySelector('#dialog'),dialogBody=document.querySelector('#dialog-body');
let bank=[],sources=[],assetManifest={},qmap=new Map(),packCache=new Map();
let state={active:null,history:[],wrong:{}},tab='practice',view='home',resultId='',showMastered=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const grade=(q,a)=>q.unscored||!q.answer?'unscored':a===q.answer?'correct':'wrong';
const complete=(q,a)=>{if(!a)return false;const keys=q.options.map(o=>o.key);if(q.kind==='ranking'){const p=a.split('|');return p.length===2&&p[0]!==p[1]&&p.every(k=>keys.includes(k))}return keys.includes(a)};
function persist(){localStorage.setItem(STORE,JSON.stringify(state))}
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORE));if(x&&Array.isArray(x.history)&&x.wrong)state=x}catch{}}
function progress(value){return `<div class="progress"><i style="width:${Math.max(0,Math.min(100,value))}%"></i></div>`}
function shell(content){return `<div class="shell"><header class="topbar"><button class="brand" data-do="home">十<b>题</b>一练<b>.</b></button><span class="save">✓ 进度保存在当前设备</span></header>${content}<footer>十题一练 · 日积跬步，终至千里。</footer></div>`}
function tabs(){return `<nav class="tabs"><button data-tab="practice" class="${tab==='practice'?'active':''}">分类练习</button><button data-tab="wrong" class="${tab==='wrong'?'active':''}">错题集 ${pending().length}</button><button data-tab="history" class="${tab==='history'?'active':''}">练习记录</button></nav>`}
const pending=()=>Object.entries(state.wrong).filter(([,w])=>!w.mastered);
function home(){
 const top=`<section class="hero"><div><p class="eyebrow">专注这一组</p><h1>每天进步，从十题开始。</h1><p class="muted">选一个题型，完成后一起看答案。</p></div><div class="stats"><div><strong>${state.history.length}</strong><span>已完成组数</span></div><div><strong>${pending().length}</strong><span>待复习错题</span></div></div></section>${tabs()}`;
 let content='';
 if(tab==='practice'){
  const active=state.active?`<section class="resume"><div><small>上次练到这里</small><br><strong>${esc(state.active.category)} · 已答 ${state.active.ids.filter(id=>complete(qmap.get(id),state.active.answers[id])).length}/${state.active.ids.length} 题</strong></div><button class="primary" data-do="resume">继续练习</button></section>`:'';
  const cards=CATEGORIES.map((name,i)=>{const count=bank.filter(q=>q.category===name).length;const done=new Set(state.history.filter(s=>s.mode==='normal'&&s.category===name).flatMap(s=>s.ids)).size;return `<article class="card"><div class="card-top"><span class="icon">${ICONS[i]}</span><span class="number">0${i+1}</span></div><h2>${name}</h2><p>${DESCRIPTIONS[i]}</p>${progress(count?done/count*100:0)}<p>${done}/${count} 题</p><button class="start" data-start="${name}" ${done>=count?'disabled':''}>${done>=count?'本题型已完成':'开始一组　→'}</button></article>`}).join('');
  content=`${active}<div class="heading"><h2>选择题型</h2><span class="muted">已导入 ${bank.length.toLocaleString()} 题 · 每组最多 10 题</span></div><section class="grid">${cards}</section><div class="source-note"><span>完成一组后统一查看答案与解析。性格测试不计入正确率。</span><button class="link-button" data-do="sources">题库导入情况 →</button></div>`;
 }else if(tab==='wrong'){
  const rows=Object.entries(state.wrong).filter(([,w])=>w.mastered===showMastered).map(([id,w])=>row(qmap.get(id),showMastered?'✓':'×',`${qmap.get(id).category} · 累计错 ${w.count} 次`,id,showMastered?'ok':'bad')).join('');
  content=`<div class="heading"><h2>${showMastered?'已掌握的错题':'再练一次，记得更牢'}</h2><button class="link-button" data-do="toggle-mastered">${showMastered?'查看待复习':'查看已掌握'}</button></div>${pending().length&&!showMastered?'<button class="primary" data-do="retry">重练一组错题</button>':''}<div class="review-list">${rows||`<div class="empty"><h2>${showMastered?'还没有已掌握的错题':'目前没有待复习错题'}</h2><p>${showMastered?'错题重练答对后会保留在这里。':'完成分类练习后，答错的题会自动收录。'}</p></div>`}</div>`;
 }else{
  const rows=state.history.map(s=>{const score=s.ids.filter(id=>grade(qmap.get(id),s.answers[id])==='correct').length;return `<button class="history-row" data-review="${s.id}"><span class="icon">✓</span><div><strong>${esc(s.category)}</strong><p class="muted">${new Date(s.submitted).toLocaleString('zh-CN')} · ${s.ids.length} 题</p></div><strong>${score} 题正确</strong></button>`}).join('');
  content=`<div class="heading"><h2>每一次练习，都有记录</h2><span class="muted">${state.history.length} 组</span></div>${rows||'<div class="empty"><h2>从第一组开始</h2><p>交卷后，可随时查看结果和解析。</p></div>'}`;
 }
 root.innerHTML=shell(top+content);bind();
}
function row(q,symbol,meta,id,kind=''){return `<button class="review-row" data-detail="${esc(id)}"><span class="dot ${kind}">${symbol}</span><div><span class="row-meta">${esc(meta)}</span><p>${esc(q.stem)}</p></div><span class="muted">查看解析 ›</span></button>`}
function pictures(urls=[]){return urls.map(url=>`<button class="image-button" data-zoom="${esc(url)}"><span class="image-loading">正在读取原题图片…</span><img hidden data-asset="${esc(url)}" alt="原题图片"></button>`).join('')}
function questionBody(q){return `<div class="stem">${esc(q.stem)}</div>${pictures(q.images)}`}
function quiz(){const s=state.active;if(!s){view='home';return render()}const q=qmap.get(s.ids[s.index]),answered=s.ids.filter(id=>complete(qmap.get(id),s.answers[id])).length;
 const options=q.kind==='ranking'?`<div class="ranking">${['最符合我','最不符合我'].map((label,ri)=>`<section><h3>${label}</h3>${q.options.map(o=>`<label class="option"><input type="radio" name="rank${ri}" data-rank="${ri}" value="${esc(o.key)}" ${(s.answers[q.id]||'|').split('|')[ri]===o.key?'checked':''}><b>${esc(o.key)}</b><span>${esc(o.text)}</span></label>`).join('')}</section>`).join('')}</div><p class="muted">两项选择不能相同，本题不计分。</p>`:`<div class="options">${q.options.map(o=>`<label class="option ${s.answers[q.id]===o.key?'chosen':''}"><input type="radio" name="answer" value="${esc(o.key)}" ${s.answers[q.id]===o.key?'checked':''}><span class="letter">${esc(o.key)}</span><span>${esc(o.text)}${pictures(o.images)}</span></label>`).join('')}</div>`;
 const nums=s.ids.map((id,i)=>`<button data-index="${i}" class="${s.answers[id]?'answered ':''}${i===s.index?'current':''}">${i+1}</button>`).join('');
 root.innerHTML=shell(`<div class="practice-top"><button class="back" data-do="home">← 返回首页</button><span class="muted">${esc(s.category)} · 本组 ${s.ids.length} 题</span></div><div class="quiz-layout"><section class="question"><div class="qtop"><span class="pill">${esc(q.category)}${q.unscored?' · 不计分':''}</span><span class="qnum">${String(s.index+1).padStart(2,'0')} <small>/ ${s.ids.length}</small></span></div>${q.unscored&&q.category!=='性格测试'?'<p class="warning">本题参考答案待核实，暂不判对错。</p>':''}${questionBody(q)}${options}<p class="source">来源：${esc(q.source)} · 第 ${q.number} 题</p><div class="actions"><button class="secondary" data-prev ${s.index===0?'disabled':''}>← 上一题</button>${s.index<s.ids.length-1?'<button class="primary" data-next>下一题 →</button>':`<button class="primary" data-submit ${answered!==s.ids.length?'disabled':''}>提交本组 ✓</button>`}</div>${s.index===s.ids.length-1&&answered!==s.ids.length?`<p class="warning">还有 ${s.ids.length-answered} 题未答，请点击题号补答。</p>`:''}</section><aside class="answer-card"><h2>本组答题卡</h2><p class="muted">已答 ${answered}/${s.ids.length} 题</p>${progress(answered/s.ids.length*100)}<div class="answer-grid">${nums}</div><p class="muted">答题进度自动保存在当前设备。</p></aside></div>`);bind();activateImages();
}
function result(){const s=state.history.find(x=>x.id===resultId);if(!s){view='home';return render()}const qs=s.ids.map(id=>qmap.get(id)).filter(Boolean),correct=qs.filter(q=>grade(q,s.answers[q.id])==='correct').length,wrong=qs.filter(q=>grade(q,s.answers[q.id])==='wrong').length,unscored=qs.length-correct-wrong;
 const rows=qs.map((q,i)=>{const g=grade(q,s.answers[q.id]);return row(q,g==='correct'?'✓':g==='wrong'?'×':i+1,`第 ${i+1} 题 · ${g==='correct'?'正确':g==='wrong'?'错误':'不计分'} · 我的答案 ${s.answers[q.id]}`,q.id,g==='correct'?'ok':g==='wrong'?'bad':'')}).join('');
 root.innerHTML=shell(`<div class="practice-top"><button class="back" data-do="home">← 返回首页</button><span class="muted">${esc(s.category)} · 本组复盘</span></div><section class="result-head"><div><p class="eyebrow">本组已完成</p><h1>再看一眼，学得更扎实。</h1><p class="muted">点击题目查看答案与解析，错题已自动收录。</p></div><div class="score"><strong>${correct+wrong?Math.round(correct/(correct+wrong)*100)+'%':'—'}</strong><span>本组正确率</span></div></section><div class="counts"><span class="ok">正确 ${correct}</span><span class="bad">错误 ${wrong}</span>${unscored?`<span>不计分 ${unscored}</span>`:''}<span class="muted">共 ${qs.length} 题</span></div><div class="review-list">${rows}</div><div class="bottom"><button class="secondary" data-do="wrong">去错题集</button><button class="primary" data-more="${esc(s.category)}">继续下一组 →</button></div>`);bind();
}
function start(category,mode='normal'){if(state.active){view='quiz';return render()}let pool=bank.filter(q=>category==='错题重练'||q.category===category);if(mode==='wrong')pool=pool.filter(q=>state.wrong[q.id]&&!state.wrong[q.id].mastered);else{const done=new Set(state.history.filter(s=>s.mode==='normal').flatMap(s=>s.ids));pool=pool.filter(q=>!done.has(q.id))}if(!pool.length)return;state.active={id:uid(),category,ids:pool.slice(0,10).map(q=>q.id),answers:{},index:0,started:new Date().toISOString(),mode};persist();view='quiz';render();scrollTo(0,0)}
function submit(){const s=state.active;if(!s||s.ids.some(id=>!complete(qmap.get(id),s.answers[id])))return;s.submitted=new Date().toISOString();for(const id of s.ids){const g=grade(qmap.get(id),s.answers[id]);if(g==='wrong'){const p=state.wrong[id];state.wrong[id]={count:(p?.count||0)+1,answer:s.answers[id],mastered:false,last:s.submitted}}else if(g==='correct'&&state.wrong[id])state.wrong[id].mastered=true}state.history.unshift(s);state.active=null;resultId=s.id;view='result';persist();render();scrollTo(0,0)}
function detail(id){const q=qmap.get(id);dialogBody.innerHTML=`<h2>题目解析</h2><p class="muted">${esc(q.category)} · ${esc(q.source)}</p><div class="dialog-scroll">${questionBody(q)}${q.options.map(o=>`<div class="detail-option ${q.answer===o.key?'answer':''}"><b>${esc(o.key)}.</b> ${esc(o.text)}${pictures(o.images)}</div>`).join('')}<section class="explain"><span class="pill">${esc(q.unscored?'不计分':q.answerSource||'待核实')}</span><h3>${q.answer?`参考答案：${esc(q.answer)}`:'暂无客观标准答案'}</h3><p>${esc(q.explanation)}</p>${pictures(q.explanationImages)}${q.note?`<p class="warning">${esc(q.note)}</p>`:''}</section></div>`;dialog.showModal();activateImages()}
function sourceDialog(){dialogBody.innerHTML=`<h2>题库导入情况</h2><p class="muted">题目由原文件提取；未能可靠核实的内容不会计分。</p><div class="dialog-scroll">${sources.map(s=>`<div class="source-item"><strong>${esc(s.name)}</strong><p>${esc(s.status)}</p></div>`).join('')}</div>`;dialog.showModal()}
async function loadPack(name){if(packCache.has(name))return packCache.get(name);const job=(async()=>{if(!('DecompressionStream'in window))throw new Error('浏览器版本过旧');const buf=await(await fetch(name)).arrayBuffer();const raw=await new Response(new Blob([buf]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();const bytes=new Uint8Array(raw),files=new Map();let off=0;while(off+512<=bytes.length){const header=bytes.slice(off,off+512);if(header.every(x=>x===0))break;const fileName=new TextDecoder().decode(header.slice(0,100)).replace(/\0.*$/,'');const sizeText=new TextDecoder().decode(header.slice(124,136)).replace(/\0.*$/,'').trim();const size=parseInt(sizeText||'0',8);off+=512;const blob=new Blob([bytes.slice(off,off+size)],{type:'image/webp'});files.set(fileName,URL.createObjectURL(blob));off+=Math.ceil(size/512)*512}return files})();packCache.set(name,job);return job}
async function activateImages(){for(const img of document.querySelectorAll('img[data-asset]')){const key=img.dataset.asset.replace(/^\//,'');try{const files=await loadPack(assetManifest[key]);img.src=files.get(key);img.hidden=false;img.previousElementSibling?.remove()}catch{img.parentElement.innerHTML='<span class="warning">图片读取失败，请刷新或更换浏览器。</span>'}}}
function bind(){
 document.querySelectorAll('[data-do="home"]').forEach(x=>x.onclick=()=>{view='home';tab='practice';render()});
 document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});
 document.querySelectorAll('[data-start]').forEach(x=>x.onclick=()=>start(x.dataset.start));
 document.querySelector('[data-do="resume"]')?.addEventListener('click',()=>{view='quiz';render()});
 document.querySelector('[data-do="sources"]')?.addEventListener('click',sourceDialog);
 document.querySelector('[data-do="toggle-mastered"]')?.addEventListener('click',()=>{showMastered=!showMastered;render()});
 document.querySelector('[data-do="retry"]')?.addEventListener('click',()=>start('错题重练','wrong'));
 document.querySelector('[data-do="wrong"]')?.addEventListener('click',()=>{view='home';tab='wrong';render()});
 document.querySelectorAll('[data-review]').forEach(x=>x.onclick=()=>{resultId=x.dataset.review;view='result';render()});
 document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>detail(x.dataset.detail));
 document.querySelectorAll('[data-index]').forEach(x=>x.onclick=()=>{state.active.index=Number(x.dataset.index);persist();render()});
 document.querySelector('[data-prev]')?.addEventListener('click',()=>{state.active.index--;persist();render()});
 document.querySelector('[data-next]')?.addEventListener('click',()=>{state.active.index++;persist();render();scrollTo(0,0)});
 document.querySelector('[data-submit]')?.addEventListener('click',submit);
 document.querySelector('[data-more]')?.addEventListener('click',e=>start(e.currentTarget.dataset.more));
 document.querySelectorAll('input[name="answer"]').forEach(x=>x.onchange=()=>{state.active.answers[qmap.get(state.active.ids[state.active.index]).id]=x.value;persist();render()});
 document.querySelectorAll('[data-rank]').forEach(x=>x.onchange=()=>{const q=qmap.get(state.active.ids[state.active.index]),parts=(state.active.answers[q.id]||'|').split('|');parts[Number(x.dataset.rank)]=x.value;if(parts[0]===parts[1])parts[1-Number(x.dataset.rank)]='';state.active.answers[q.id]=parts.join('|');persist();render()});
 document.querySelectorAll('[data-zoom]').forEach(x=>x.onclick=e=>{e.preventDefault();dialogBody.innerHTML=`<h2>原题图片</h2>${pictures([x.dataset.zoom])}`;dialog.showModal();activateImages()});
}
function render(){view==='home'?home():view==='quiz'?quiz():result()}
dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
try{[bank,sources,assetManifest]=await Promise.all([fetch('bank.json').then(r=>r.json()),fetch('sources.json').then(r=>r.json()),fetch('assets.json').then(r=>r.json())]);qmap=new Map(bank.map(q=>[q.id,q]));loadState();render()}catch(e){root.innerHTML='<div class="loading">题库读取失败，请刷新页面重试。</div>';console.error(e)}
